package de.rwth.idsg.steve.mq.message;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import lombok.Setter;
import lombok.experimental.SuperBuilder;

/**
 * @author ralf.heese
 */
@Getter
@Setter
@SuperBuilder
@NoArgsConstructor
public class ChargePointOperationResponse implements OperationResponse {

    /** Action causing the error */
    @NonNull
    private String action;

    /** Globally unique identifier of the request generated by the origin of the request (e.g., ID of the cloud event) */
    @NonNull
    private String messageId;

    /** Unique ID of the charge point (aka charge box) */
    @NonNull
    private String chargePointId;
}
