package de.rwth.idsg.steve.mq.message;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import lombok.Setter;
import lombok.experimental.SuperBuilder;

/**
 * @author ralf.heese
 */
@Getter
@Setter
@SuperBuilder
@NoArgsConstructor
public class ChargePointOperationRequest implements OperationRequest {

    /** Action to be performed */
    @NonNull
    private String action;

    /** Globally unique identifier of the request generated by the origin of the request (e.g., ID of the cloud event) */
    @NonNull
    private String messageId;

    /** Unique ID of the charge point (aka charge box) */
    @NonNull
    private String chargePointId;

    /** ID of the connector (supposed to be greater than 0) */
    private Integer connectorId;
}
